INSERT INTO `photos`(`id`, `title`, `description`, `url`, `visible`) VALUES ('1','Micheal e Pam','due ragazzi in una posa informale','https://images.pexels.com/photos/5325791/pexels-photo-5325791.jpeg?auto=compress&cs=tinysrgb&w=1600',TRUE);
INSERT INTO `photos`(`id`, `title`, `description`, `url`, `visible`) VALUES ('2','Pontile','pontile con lago, foto senza filtri','https://images.pexels.com/photos/206359/pexels-photo-206359.jpeg?auto=compress&cs=tinysrgb&w=1600',TRUE);
INSERT INTO `photos`(`id`, `title`, `description`, `url`, `visible`) VALUES ('3','Jack e Anna','due fotografi mentre valutano i loro scatti','https://images.pexels.com/photos/6271528/pexels-photo-6271528.jpeg?auto=compress&cs=tinysrgb&w=1600',TRUE);
INSERT INTO `photos`(`id`, `title`, `description`, `url`, `visible`) VALUES ('4','Montagna','paesaggio di montagna al tramonto','https://images.pexels.com/photos/346529/pexels-photo-346529.jpeg?auto=compress&cs=tinysrgb&w=1600',TRUE);
INSERT INTO `photos`(`id`, `title`, `description`, `url`, `visible`) VALUES ('5','Polpo','polpo sul fondale','https://images.pexels.com/photos/3046629/pexels-photo-3046629.jpeg?auto=compress&cs=tinysrgb&w=1600',TRUE);
INSERT INTO `photos`(`id`, `title`, `description`, `url`, `visible`) VALUES ('6','Anguria','scatto frutta estiva','https://images.pexels.com/photos/5946081/pexels-photo-5946081.jpeg?auto=compress&cs=tinysrgb&w=1600',TRUE);
INSERT INTO `photos`(`id`, `title`, `description`, `url`, `visible`) VALUES ('7','La Pera','scatto frutto autunnale','https://images.pexels.com/photos/5325791/pexels-photo-5325791.jpeg?auto=compress&cs=tinysrgb&w=1600',TRUE);
INSERT INTO `photos`(`id`, `title`, `description`, `url`, `visible`) VALUES ('8','Il Cavallo','cavallo in bianco e nero','https://images.pexels.com/photos/1687926/pexels-photo-1687926.jpeg?auto=compress&cs=tinysrgb&w=1600',TRUE);
INSERT INTO `photos`(`id`, `title`, `description`, `url`, `visible`) VALUES ('9','Treno','treno con paesaggio urbano','https://images.pexels.com/photos/16775511/pexels-photo-16775511/free-photo-of-citta-allenare-viaggio-trasporto.jpeg?auto=compress&cs=tinysrgb&w=1600',TRUE);
